# TCL File Generated by Component Editor 25.1
# Sun May 17 02:28:06 MSK 2026
# DO NOT MODIFY


# 
# avmm_exporter "avmm_exporter" v1.0
#  2026.05.17.02:28:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avmm_exporter
# 
set_module_property DESCRIPTION ""
set_module_property NAME avmm_exporter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avmm_exporter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avmm_exporter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_exporter.sv SYSTEM_VERILOG PATH ../../../../rtl/src/avmm_dma/avmm_exporter.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AVMM_DATA_WIDTH INTEGER 128 ""
set_parameter_property AVMM_DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property AVMM_DATA_WIDTH DISPLAY_NAME AVMM_DATA_WIDTH
set_parameter_property AVMM_DATA_WIDTH TYPE INTEGER
set_parameter_property AVMM_DATA_WIDTH UNITS None
set_parameter_property AVMM_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVMM_DATA_WIDTH DESCRIPTION ""
set_parameter_property AVMM_DATA_WIDTH HDL_PARAMETER true
add_parameter AVMM_ADDR_WIDTH INTEGER 64 ""
set_parameter_property AVMM_ADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property AVMM_ADDR_WIDTH DISPLAY_NAME AVMM_ADDR_WIDTH
set_parameter_property AVMM_ADDR_WIDTH TYPE INTEGER
set_parameter_property AVMM_ADDR_WIDTH UNITS None
set_parameter_property AVMM_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVMM_ADDR_WIDTH DESCRIPTION ""
set_parameter_property AVMM_ADDR_WIDTH HDL_PARAMETER true
add_parameter AVMM_BURST_WIDTH INTEGER 6 ""
set_parameter_property AVMM_BURST_WIDTH DEFAULT_VALUE 6
set_parameter_property AVMM_BURST_WIDTH DISPLAY_NAME AVMM_BURST_WIDTH
set_parameter_property AVMM_BURST_WIDTH TYPE INTEGER
set_parameter_property AVMM_BURST_WIDTH UNITS None
set_parameter_property AVMM_BURST_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVMM_BURST_WIDTH DESCRIPTION ""
set_parameter_property AVMM_BURST_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avmm_s
# 
add_interface avmm_s avalon end
set_interface_property avmm_s addressUnits SYMBOLS
set_interface_property avmm_s associatedClock clock
set_interface_property avmm_s associatedReset reset_sink
set_interface_property avmm_s bitsPerSymbol 8
set_interface_property avmm_s burstOnBurstBoundariesOnly false
set_interface_property avmm_s burstcountUnits WORDS
set_interface_property avmm_s explicitAddressSpan 0
set_interface_property avmm_s holdTime 0
set_interface_property avmm_s linewrapBursts false
set_interface_property avmm_s maximumPendingReadTransactions 1
set_interface_property avmm_s maximumPendingWriteTransactions 0
set_interface_property avmm_s readLatency 0
set_interface_property avmm_s readWaitTime 1
set_interface_property avmm_s setupTime 0
set_interface_property avmm_s timingUnits Cycles
set_interface_property avmm_s writeWaitTime 0
set_interface_property avmm_s ENABLED true
set_interface_property avmm_s EXPORT_OF ""
set_interface_property avmm_s PORT_NAME_MAP ""
set_interface_property avmm_s CMSIS_SVD_VARIABLES ""
set_interface_property avmm_s SVD_ADDRESS_GROUP ""

add_interface_port avmm_s avmm_s_chipselect chipselect Input 1
add_interface_port avmm_s avmm_s_byteenable byteenable Input "(((AVMM_DATA_WIDTH/8)-1)) - (0) + 1"
add_interface_port avmm_s avmm_s_readdata readdata Output "((AVMM_DATA_WIDTH-1)) - (0) + 1"
add_interface_port avmm_s avmm_s_writedata writedata Input "((AVMM_DATA_WIDTH-1)) - (0) + 1"
add_interface_port avmm_s avmm_s_read read Input 1
add_interface_port avmm_s avmm_s_write write Input 1
add_interface_port avmm_s avmm_s_burstcount burstcount Input "((AVMM_BURST_WIDTH-1)) - (0) + 1"
add_interface_port avmm_s avmm_s_readdatavalid readdatavalid Output 1
add_interface_port avmm_s avmm_s_waitrequest waitrequest Output 1
add_interface_port avmm_s avmm_s_address address Input "((AVMM_ADDR_WIDTH-1)) - (0) + 1"
set_interface_assignment avmm_s embeddedsw.configuration.isFlash 0
set_interface_assignment avmm_s embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm_s embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm_s embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avmm_m
# 
add_interface avmm_m avalon start
set_interface_property avmm_m addressUnits SYMBOLS
set_interface_property avmm_m associatedClock clock
set_interface_property avmm_m associatedReset reset_sink
set_interface_property avmm_m bitsPerSymbol 8
set_interface_property avmm_m burstOnBurstBoundariesOnly false
set_interface_property avmm_m burstcountUnits WORDS
set_interface_property avmm_m doStreamReads false
set_interface_property avmm_m doStreamWrites false
set_interface_property avmm_m holdTime 0
set_interface_property avmm_m linewrapBursts false
set_interface_property avmm_m maximumPendingReadTransactions 0
set_interface_property avmm_m maximumPendingWriteTransactions 0
set_interface_property avmm_m readLatency 0
set_interface_property avmm_m readWaitTime 1
set_interface_property avmm_m setupTime 0
set_interface_property avmm_m timingUnits Cycles
set_interface_property avmm_m writeWaitTime 0
set_interface_property avmm_m ENABLED true
set_interface_property avmm_m EXPORT_OF ""
set_interface_property avmm_m PORT_NAME_MAP ""
set_interface_property avmm_m CMSIS_SVD_VARIABLES ""
set_interface_property avmm_m SVD_ADDRESS_GROUP ""

add_interface_port avmm_m avmm_m_chipselect chipselect Output 1
add_interface_port avmm_m avmm_m_byteenable byteenable Output AVMM_DATA_WIDTH/8
add_interface_port avmm_m avmm_m_readdata readdata Input AVMM_DATA_WIDTH
add_interface_port avmm_m avmm_m_writedata writedata Output AVMM_DATA_WIDTH
add_interface_port avmm_m avmm_m_read read Output 1
add_interface_port avmm_m avmm_m_write write Output 1
add_interface_port avmm_m avmm_m_burstcount burstcount Output "((AVMM_BURST_WIDTH-1)) - (0) + 1"
add_interface_port avmm_m avmm_m_readdatavalid readdatavalid Input 1
add_interface_port avmm_m avmm_m_waitrequest waitrequest Input 1
add_interface_port avmm_m avmm_m_address address Output AVMM_ADDR_WIDTH


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1

