name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ALTERA_TOOLS_ARGS: "--mount type=bind,src=$PWD,dst=/mnt/work --mac-address=${{ secrets.LM_LICENSE_MAC }} --workdir=/mnt/work --network=bridge"

jobs:
  pull_docker_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.dockerhub_token }}

      - name: Run docker image tests
        shell: bash
        run: |
          chmod +x build_system/autotest/configure
          docker run ${{env.ALTERA_TOOLS_ARGS}} ${{ secrets.docker_username }}/altera_tools:latest "./build_system/autotest/configure --prefix=QUESTA; \
          make -f build_system/cctb/makefile run; \
          make -f build_system/autotest/makefile run_pytest TESTS_DIRS=tb/tb_dma_csr"
        timeout-minutes: 15

      - name: Run full pytest
        shell: bash
        run: docker run ${{env.ALTERA_TOOLS_ARGS}} ${{ secrets.docker_username }}/altera_tools:latest "make -f build_system/autotest/makefile run_pytest"
        timeout-minutes: 120

      - name: Run quartus release
        shell: bash
        run: docker run ${{env.ALTERA_TOOLS_ARGS}} ${{ secrets.DOCKER_USERNAME }}/altera_tools:latest "make -f build_system/quartus/makefile create_releases"
        timeout-minutes: 60

      - name: Archive artifacts
        shell: bash
        run: tar -cvf ${{ runner.temp }}/logs.tar ./.cache

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_system_logs
          path: ${{ runner.temp }}/logs.tar